### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shuwang21** [350HP/AmexOffers#1]
Basically, it cannot obtain the right amount of cards in your account.

**Comment by shuwang21** [comment]
Excellent tools. Thank the author.

To fix the problem.
1. Change the "app__card__" to be "axp-account-selector__app__card__"
2. comment out "wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//span[starts-with(@class,'GlobalHeader__closed___')]")));"

**Comment by j-justice** [comment]
Were you by chance able to get this working? I know you'd posted the above suggested edits. 

I'm not sure which files to change.

**Comment by ghost** [comment]
@swUchicago I updated what you noted, changing app__card__ to the axp and commented out the other part and it still errored out. 

Any ideas?
